library(plyr)
library(ggplot2)
library(reshape2)
library(devtools) # Requires R CURL: sudo apt install r-cran-curl
library(ggbiplot)
library(RColorBrewer)
library(dplyr)
library(factoextra)
library(numbers)
library(data.table)
library(BiocManager)
#BiocManager::install('rhdf5') # must be installed but otherwise you don't need this line
library(rhdf5)
library(paletteer)
library(zoo)
require(gridExtra)
library(animation)
library(egg)
library(stringr)
